CategoryL.create!([
  {name: "レディース"},
  {name: "メンズ"},
  {name: "キッズ"},
  {name: "インテリア・住まい・小物"},
  {name: "本・音楽・ゲーム"}
])
CategoryM.create!([
  {name: "トップス", category_l_id: 1},
  {name: "パンツ", category_l_id: 1},
  {name: "スカート", category_l_id: 1},
  {name: "ワンピース", category_l_id: 1},
  {name: "アクセサリー", category_l_id: 1},
  {name: "トップス", category_l_id: 2},
  {name: "ジャケット・アウター", category_l_id: 2},
  {name: "靴", category_l_id: 2},
  {name: "バッグ", category_l_id: 2},
  {name: "スーツ", category_l_id: 2},
  {name: "キッズ服（女の子）", category_l_id: 3},
  {name: "キッズ服（男の子）", category_l_id: 3},
  {name: "キッズ靴", category_l_id: 3},
  {name: "おもちゃ", category_l_id: 3},
  {name: "キッズ用ファッション小物", category_l_id: 3},
  {name: "キッチン・食器", category_l_id: 4},
  {name: "椅子・チェア", category_l_id: 4},
  {name: "机・テーブル", category_l_id: 4},
  {name: "本", category_l_id: 5},
  {name: "音楽", category_l_id: 5},
  {name: "ゲーム", category_l_id: 5}
])
CategoryS.create!([
  {name: "Tシャツ", category_m_id: 1},
  {name: "シャツ", category_m_id: 1},
  {name: "ニット", category_m_id: 1},
  {name: "パーカー・スウェット", category_m_id: 1},
  {name: "デニム・ジーンズ", category_m_id: 2},
  {name: "ショートパンツ", category_m_id: 2},
  {name: "チノパン", category_m_id: 2},
  {name: "カジュアルパンツ", category_m_id: 2},
  {name: "ミニスカート", category_m_id: 3},
  {name: "膝丈スカート", category_m_id: 3},
  {name: "ロングスカート", category_m_id: 3},
  {name: "ミニワンピース", category_m_id: 4},
  {name: "膝丈ワンピース", category_m_id: 4},
  {name: "ロングワンピース", category_m_id: 4},
  {name: "ネックレス", category_m_id: 5},
  {name: "ブレスレット", category_m_id: 5},
  {name: "リング", category_m_id: 5},
  {name: "ピアス", category_m_id: 5},
  {name: "Tシャツ", category_m_id: 6},
  {name: "シャツ", category_m_id: 6},
  {name: "タンクトップ", category_m_id: 6},
  {name: "スウェット", category_m_id: 6},
  {name: "テーラードジャケット", category_m_id: 7},
  {name: "デニムジャケット", category_m_id: 7},
  {name: "ダウンジャケット", category_m_id: 7},
  {name: "ダッフルコート", category_m_id: 7},
  {name: "スニーカー", category_m_id: 8},
  {name: "サンダル", category_m_id: 8},
  {name: "ブーツ", category_m_id: 8},
  {name: "ビジネスシューズ", category_m_id: 8},
  {name: "ショルダーバッグ", category_m_id: 9},
  {name: "トートバッグ", category_m_id: 9},
  {name: "ビジネスバッグ", category_m_id: 9},
  {name: "ボストンバッグ", category_m_id: 9},
  {name: "スーツジャケット", category_m_id: 10},
  {name: "スラックス", category_m_id: 10},
  {name: "ベスト", category_m_id: 10},
  {name: "セットアップ", category_m_id: 10},
  {name: "トップス", category_m_id: 11},
  {name: "ボトムス", category_m_id: 11},
  {name: "パジャマ", category_m_id: 11},
  {name: "トップス", category_m_id: 12},
  {name: "ボトムス", category_m_id: 12},
  {name: "パジャマ", category_m_id: 12},
  {name: "スニーカー", category_m_id: 13},
  {name: "サンダル", category_m_id: 13},
  {name: "ブーツ", category_m_id: 13},
  {name: "長靴", category_m_id: 13},
  {name: "お風呂おもちゃ", category_m_id: 14},
  {name: "ガラガラ", category_m_id: 14},
  {name: "オルゴール", category_m_id: 14},
  {name: "ベビージム", category_m_id: 14},
  {name: "帽子", category_m_id: 15},
  {name: "傘", category_m_id: 15},
  {name: "手袋", category_m_id: 15},
  {name: "食器", category_m_id: 16},
  {name: "調理器具", category_m_id: 16},
  {name: "弁当用品", category_m_id: 16},
  {name: "デスクチェア", category_m_id: 17},
  {name: "ダイニングチェア", category_m_id: 17},
  {name: "折りたたみ椅子", category_m_id: 17},
  {name: "こたつ", category_m_id: 18},
  {name: "ダイニングテーブル", category_m_id: 18},
  {name: "PCデスク", category_m_id: 18},
  {name: "ちゃぶ台", category_m_id: 18},
  {name: "小説", category_m_id: 19},
  {name: "マンガ", category_m_id: 19},
  {name: "雑誌", category_m_id: 19},
  {name: "CD", category_m_id: 20},
  {name: "レコード", category_m_id: 20},
  {name: "  楽器", category_m_id: 20},
  {name: "ゲーム本体", category_m_id: 21},
  {name: "ゲームソフト", category_m_id: 21}
])
Size.create!([
  {category_s_id: "1", name: "XS"},
  {category_s_id: "1", name: "S"},
  {category_s_id: "1", name: "M"},
  {category_s_id: "1", name: "L"},
  {category_s_id: "1", name: "XL"}
])
